#pragma once
// iOS stand-in for the NDK's <android/keycodes.h>. Only the Android Java
// keyboard bridge feeds these codes; on iOS that path never runs, so the
// constants exist just so the shared mapping tables compile. Values match the
// NDK so the tables' case labels stay distinct.

enum {
    AKEYCODE_UNKNOWN = 0,
    AKEYCODE_BACK = 4,
    AKEYCODE_0 = 7, AKEYCODE_1 = 8, AKEYCODE_2 = 9, AKEYCODE_3 = 10, AKEYCODE_4 = 11,
    AKEYCODE_5 = 12, AKEYCODE_6 = 13, AKEYCODE_7 = 14, AKEYCODE_8 = 15, AKEYCODE_9 = 16,
    AKEYCODE_DPAD_UP = 19, AKEYCODE_DPAD_DOWN = 20, AKEYCODE_DPAD_LEFT = 21, AKEYCODE_DPAD_RIGHT = 22,
    AKEYCODE_A = 29, AKEYCODE_B = 30, AKEYCODE_C = 31, AKEYCODE_D = 32, AKEYCODE_E = 33,
    AKEYCODE_F = 34, AKEYCODE_G = 35, AKEYCODE_H = 36, AKEYCODE_I = 37, AKEYCODE_J = 38,
    AKEYCODE_K = 39, AKEYCODE_L = 40, AKEYCODE_M = 41, AKEYCODE_N = 42, AKEYCODE_O = 43,
    AKEYCODE_P = 44, AKEYCODE_Q = 45, AKEYCODE_R = 46, AKEYCODE_S = 47, AKEYCODE_T = 48,
    AKEYCODE_U = 49, AKEYCODE_V = 50, AKEYCODE_W = 51, AKEYCODE_X = 52, AKEYCODE_Y = 53,
    AKEYCODE_Z = 54,
    AKEYCODE_COMMA = 55, AKEYCODE_PERIOD = 56,
    AKEYCODE_ALT_LEFT = 57, AKEYCODE_ALT_RIGHT = 58,
    AKEYCODE_SHIFT_LEFT = 59, AKEYCODE_SHIFT_RIGHT = 60,
    AKEYCODE_TAB = 61, AKEYCODE_SPACE = 62,
    AKEYCODE_ENTER = 66, AKEYCODE_DEL = 67, AKEYCODE_GRAVE = 68,
    AKEYCODE_MINUS = 69, AKEYCODE_EQUALS = 70,
    AKEYCODE_LEFT_BRACKET = 71, AKEYCODE_RIGHT_BRACKET = 72, AKEYCODE_BACKSLASH = 73,
    AKEYCODE_SEMICOLON = 74, AKEYCODE_APOSTROPHE = 75, AKEYCODE_SLASH = 76,
    AKEYCODE_PAGE_UP = 92, AKEYCODE_PAGE_DOWN = 93,
    AKEYCODE_ESCAPE = 111, AKEYCODE_FORWARD_DEL = 112,
    AKEYCODE_CTRL_LEFT = 113, AKEYCODE_CTRL_RIGHT = 114,
    AKEYCODE_MOVE_HOME = 122, AKEYCODE_MOVE_END = 123, AKEYCODE_INSERT = 124,
    AKEYCODE_NUMPAD_ENTER = 160,
};
